-- Create Dependencies Table
CREATE TABLE IF NOT EXISTS public.project_dependencies (
    id bigint generated by default as identity primary key,
    source_project_id bigint not null references public.projects(id) on delete cascade,
    target_project_id bigint not null references public.projects(id) on delete cascade,
    type text not null default 'finish_to_start', -- 'finish_to_start', 'start_to_start', etc.
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
ALTER TABLE public.project_dependencies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.project_dependencies
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.project_dependencies
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON public.project_dependencies
    FOR DELETE USING (auth.role() = 'authenticated');

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.project_dependencies;

-- Mock Data (Optional: Connect two projects for demo)
-- INSERT INTO public.project_dependencies (source_project_id, target_project_id)
-- SELECT p1.id, p2.id 
-- FROM public.projects p1, public.projects p2 
-- WHERE p1.status = 'EN_PROCESO' AND p2.status = 'PLANIFICACION' 
-- LIMIT 1;
